version: "3.8"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db
    ports:
      - "1500:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5001:5001"
    depends_on:
      - db
      # - client
    volumes:
      - ".:/app/"
      - D:/Users/.aspnet/https/:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  # client:
  #   container_name: client
  #   build:
  #     context: .
  #     dockerfile: ./client/Dockerfile
  #   volumes:
  #     - "./client:/app"
  #     - "/app/node_modules"
  #   ports:
  #     - "4200:4200"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
